# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 22, host: 22022, id: "ssh"
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "modifyvm", :id,
      "--name", "xenial",
      "--memory", "2048",
      "--cpus", "1",
      "--paravirtprovider", "kvm",
      "--vram", "128",
      "--accelerate3d", "on",
      "--vrde", "on",
      "--vrdeauthtype", "null",
      "--vrdemulticon", "off"
    ]
  end
  config.vm.provision :shell, path: "./provision.sh", args: "python mysql"
end
